### ISSUE TITLE
Add Crunchyroll

### ISSUE THREAD

**Issue by Warraybe** [rleroi/Stremio-Streaming-Catalogs-Addon#14]
Funimation is in the process, albeit it slow, of shutting down since it was acquired by Crunchyroll. Would it be possible to replace Funimation or add Crunchyroll?

**Comment by rleroi** [comment]
Yep we used to have Crunchyroll but I had replaced it with Funimation because it seems it had the same content. Will replace it back again ;)

**Comment by rleroi** [comment]
Merged with https://github.com/rleroi/Stremio-Streaming-Catalogs-Addon/issues/16
