### ISSUE TITLE
Add to list

### ISSUE THREAD

**Issue by jay78887** [rleroi/Stremio-Streaming-Catalogs-Addon#15]
Hi,

I've been using cyberflix which is having a lot of issues recently.
Moved over to streaming catalogues which is much easier to use and more stable.

However, cyberflix has the below, can you please add the below to the app list:
Starz
Rakuten
Kids
Anime
Asian (korean/chinese)

Appreciate it.

**Comment by jay78887** [comment]
Also, I noticed some of the lists aren't really up to date with what it looks like older shows only.
How are the lists kept up to date or pulling its' sources from?

For example, on the Discovery list, I don't see many shows from the past two years.

**Comment by rleroi** [comment]
It gets results from https://www.justwatch.com/
If it is on there, I can add it.

It should be showing results from this page, in the same order: https://www.justwatch.com/us/provider/discovery-plus/tv-shows
If not, I can look into it. Maybe older shows are more popular?

**Comment by rleroi** [comment]
Merged with https://github.com/rleroi/Stremio-Streaming-Catalogs-Addon/issues/16
