### ISSUE TITLE
Add-on is not installing

### ISSUE THREAD

**Issue by CodElixer** [rleroi/Stremio-Streaming-Catalogs-Addon#17]
Now post configuration of the catalogue, Add-on is not installing and showing error! It's happening on both Android and Windows.
![Screenshot_20240318-231457_Stremio.png](https://github.com/rleroi/Stremio-Streaming-Catalogs-Addon/assets/40817467/0ccc14df-0932-48ca-b6ec-90ae16dcee2b)

**Comment by rleroi** [comment]
I can't reproduce this, maybe it was a bug in Stremio
