### ISSUE TITLE
This addon returned empty content

### ISSUE THREAD

**Issue by Godfather096** [rleroi/Stremio-Streaming-Catalogs-Addon#21]
When installing i just get the message 'this addon returned empty content' when browsing catalogs.

**Comment by wsamipw** [comment]
similar issue
![Screenshot from 2024-07-25 08-46-54](https://github.com/user-attachments/assets/0ecc389d-26de-4119-9ab8-2756da5854cf)

**Comment by rleroi** [comment]
The beamup server was blocked by the justwatch API. This seems to be solved for now.
