### ISSUE TITLE
Unable to enter free RPDB key

### ISSUE THREAD

**Issue by TrojanZX** [rleroi/Stremio-Streaming-Catalogs-Addon#24]
After clicking on install addon, the rpdb column says "please match the requested format". I'm pretty sure i'm using the api i got from rpdb (free api).

**Comment by jaruba** [comment]
i opened a pull request for this: https://github.com/rleroi/Stremio-Streaming-Catalogs-Addon/pull/23

but the dev must merge and deploy it

**Comment by jaruba** [comment]
PR was merged
