### ISSUE TITLE
Movies and Series not showing posters 

### ISSUE THREAD

**Issue by andre-lx** [rleroi/Stremio-Streaming-Catalogs-Addon#7]
Hi. 

Since yesterday, the catalogues are not showing any poster for the movies and series.

Netflix example:
![image](https://user-images.githubusercontent.com/44682155/222970084-cc356566-337d-49b3-9117-916c5e4db2da.png)

Thanks

**Comment by vlemman** [comment]
also on android TV :)

![image](https://user-images.githubusercontent.com/17772153/222974166-8c940e7c-977f-4b89-acbc-f7c1ff54675b.jpg)

**Comment by 420tushar** [comment]
Uninstalling the add-on and then while reinstalling unselect all the services and selecting them again and installing the add-on fixed the problem

**Comment by XZTence** [comment]
> Uninstalling the add-on and then while reinstalling unselect all the services and selecting them again and installing the add-on fixed the problem

doesn't work for me, only gives me posters for funimation and curiosity stream.

**Comment by eskimgv** [comment]
I just tried but not worked for me
1-uninstall the addon
2-clear local storage & logout
3-log in
4-configure addon, unsellect all services
5-sellect only one (NF) and install
when i click the notification of addon installed before disappear posters showing up little while and disappear again

https://github.com/rleroi/Stremio-Streaming-Catalogs-Addon/assets/49225281/477c4097-d949-4c38-98c8-72e779a528e1

**Comment by rleroi** [comment]
@eskimgv It looks like the Streaming Catalogs works just fine, but the Cinemeta posters are not working for you. This is not an issue with this addon as far as I can tell.

**Comment by eskimgv** [comment]
> 

thank you for your time, i do not do anything but it works perfectly fine now
