### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by nyouness** [rleroi/Stremio-Streaming-Catalogs-Addon#9]
![Screenshot 2023-10-21 112542](https://github.com/rleroi/Stremio-Streaming-Catalogs-Addon/assets/117232906/17cbb5b4-2c65-4315-b481-c1b0d04cfbbe)

**Comment by Brandon1212b** [comment]
Trying this out to the first time. How do you log in? thats probably why its empty

**Comment by rleroi** [comment]
Fixed by #11 !
